### ISSUE TITLE
Chapter 2 Notebook does not open

### ISSUE THREAD

**Issue by mkrigba** [PacktPublishing/Principles-of-Data-Science-Second-Edition#1]
Principles-of-Data-Science-Second-Edition/Chapter02/Chapter_2%20.ipynb

![image](https://user-images.githubusercontent.com/16820461/106388616-99b8b880-639c-11eb-9fe6-7506adc58a6c.png)

**Comment by packt-pradeeps** [comment]
I've merged your pull request
